[variables]
main_domain = "${domain}"
secret_base = "${base64:64}"
db_password = "${password:32}"

[config]
mounts = []

[[config.domains]]
serviceName = "zipline"
port = 3_000
host = "${main_domain}"

[config.env]
ZIPLINE_PORT = "3000"
ZIPLINE_SECRET = "${secret_base}"
ZIPLINE_RETURN_HTTPS = "false"
ZIPLINE_LOGGER = "true"
POSTGRES_USER = "zipline"
POSTGRES_PASSWORD = "${db_password}"
POSTGRES_DB = "zipline"
DATABASE_URL = "postgres://zipline:${db_password}@postgres/zipline"
